In [2]:
#Get Station Dict
import pandas as pd
stationData = pd.DataFrame.from_csv('./data/201402_station_data.csv')
# help(sampleTripMilestones)

stationDict={}
for index, row in stationData.reset_index().iterrows():
    stationDict[row['station_id']] = row['dockcount']

In [7]:

def availableDocks(row):
    return stationDict[row['Station']] - row['Change']

stationChangesByDay = pd.DataFrame.from_csv('./extractedData/201402_StationChangesByDay.csv')
stationChangesByDay['Available'] = stationChangesByDay.apply(availableDocks,axis=1)

stationChangesByDay.to_csv('./extractedData/201402_StationChangesByDay_WithAvailable.csv',index=False)
runningLowInDay=stationChangesByDay[stationChangesByDay['Available']< 5]
runningLowInDay

In [12]:

stationChangesByHour = pd.DataFrame.from_csv('./extractedData/201402_StationChangesByHour.csv')
stationChangesByHour['Available'] = stationChangesByHour.apply(availableDocks,axis=1)

stationChangesByHour.to_csv('./extractedData/201402_StationChangesByHour_WithAvailable.csv',index=False)
runningLowInHour=stationChangesByHour[stationChangesByHour['Available']< 5]
runningLowInHour

                     Station  Change  Available
Time
2013-10-13 18:00:00       35       7          4
2013-09-07 13:00:00       48      11          4
2013-09-01 12:00:00       60      13          2
2013-09-07 12:00:00       60      11          4
2013-09-08 12:00:00       60      13          2
2013-09-19 12:00:00       60      12          3
2013-09-25 12:00:00       60      17         -2
2014-02-03 09:00:00       64      11          4
2014-02-04 09:00:00       64      11          4
2014-02-18 09:00:00       64      11          4
2013-10-02 09:00:00       65      11          4
2013-10-28 09:00:00       65      11          4
2013-12-20 17:00:00       69      22          1
2013-09-09 17:00:00       70      16          3
2013-09-23 16:00:00       70      16          3
2013-10-07 17:00:00       70      15          4
2013-10-14 17:00:00       70      16          3
2013-10-15 17:00:00       70      15          4
2013-10-16 16:00:00       70      17          2
2013-10-17 17:00:00       70      20         -1
2013-10-21 16:00:00       70      15          4
2013-10-21 17:00:00       70      19          0
2013-10-22 17:00:00       70      20         -1
2013-10-28 17:00:00       70      17          2
2013-10-29 16:00:00       70      17          2
2013-10-30 16:00:00       70      16          3
2013-10-30 17:00:00       70      22         -3
2013-10-31 16:00:00       70      17          2
2013-10-31 17:00:00       70      15          4
2013-11-04 16:00:00       70      17          2
...                      ...     ...        ...
2014-01-28 17:00:00       70      19          0
2014-01-29 17:00:00       70      16          3
2014-01-30 16:00:00       70      16          3
2014-01-31 16:00:00       70      15          4
2014-01-31 17:00:00       70      19          0
2014-02-04 16:00:00       70      22         -3
2014-02-04 17:00:00       70      16          3
2014-02-05 16:00:00       70      16          3
2014-02-05 17:00:00       70      18          1
2014-02-10 16:00:00       70      19          0
2014-02-11 16:00:00       70      18          1
2014-02-11 17:00:00       70      15          4
2014-02-12 16:00:00       70      15          4
2014-02-12 17:00:00       70      19          0
2014-02-13 16:00:00       70      19          0
2014-02-13 17:00:00       70      17          2
2014-02-14 16:00:00       70      16          3
2014-02-18 16:00:00       70      22         -3
2014-02-19 16:00:00       70      18          1
2014-02-19 17:00:00       70      23         -4
2014-02-20 16:00:00       70      16          3
2014-02-20 17:00:00       70      21         -2
2014-02-21 16:00:00       70      22         -3
2014-02-24 16:00:00       70      19          0
2014-02-24 17:00:00       70      17          2
2014-02-25 16:00:00       70      19          0
2014-02-26 16:00:00       70      15          4
2014-02-27 16:00:00       70      15          4
2014-02-27 17:00:00       70      17          2
2014-02-28 16:00:00       70      17          2

[112 rows x 3 columns]